dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.4snapshot"
  - "nightly"

matrix:
  exclude:
  allow_failures:
    - php: "nightly"
    - php: "7.4snapshot"

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: ./bin/phpspec run -fpretty

git:
  depth: 2147483647

cache:
  directories:
    - vendor
